import { ControlsIcon } from "@sanity/icons";
import { defineArrayMember, defineField, defineType } from "sanity";

import { linkFields } from "./objects";

const linkArrayMember = defineArrayMember({
  type: "object",
  name: "link",
  fields: linkFields,
  preview: { select: { title: "label", subtitle: "href" } },
});

export const siteSettings = defineType({
  name: "siteSettings",
  title: "Site Settings",
  type: "document",
  icon: ControlsIcon,
  groups: [
    { name: "general", title: "General", default: true },
    { name: "header", title: "Header" },
    { name: "footer", title: "Footer" },
    { name: "cta", title: "Footer CTA" },
    { name: "contact", title: "Contact" },
  ],
  fields: [
    defineField({
      name: "siteName",
      title: "Site Name",
      type: "string",
      group: "general",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "tagline",
      title: "Tagline",
      type: "text",
      rows: 3,
      group: "general",
      description: "Shown under the logo in the footer.",
    }),
    defineField({
      name: "newsletterTitle",
      title: "Newsletter Title",
      type: "string",
      group: "general",
    }),
    defineField({
      name: "newsletterDescription",
      title: "Newsletter Description",
      type: "text",
      rows: 2,
      group: "general",
    }),
    defineField({
      name: "navLinks",
      title: "Header Navigation",
      type: "array",
      group: "header",
      of: [linkArrayMember],
      validation: (rule) => rule.min(1),
    }),
    defineField({
      name: "headerCta",
      title: "Header Button",
      type: "object",
      group: "header",
      fields: linkFields,
    }),
    defineField({
      name: "footerServicesTitle",
      title: "Services Column Title",
      type: "string",
      group: "footer",
    }),
    defineField({
      name: "footerServiceLinks",
      title: "Services Links",
      type: "array",
      group: "footer",
      of: [linkArrayMember],
    }),
    defineField({
      name: "footerCompanyTitle",
      title: "Company Column Title",
      type: "string",
      group: "footer",
    }),
    defineField({
      name: "footerCompanyLinks",
      title: "Company Links",
      type: "array",
      group: "footer",
      of: [linkArrayMember],
    }),
    defineField({
      name: "footerContactTitle",
      title: "Contact Column Title",
      type: "string",
      group: "footer",
    }),
    defineField({
      name: "copyrightText",
      title: "Copyright Text",
      type: "string",
      group: "footer",
    }),
    defineField({
      name: "creditText",
      title: "Credit Text",
      type: "string",
      group: "footer",
      description: "Shown on the right of the copyright row.",
    }),
    defineField({
      name: "socialLinks",
      title: "Social Links",
      type: "array",
      group: "footer",
      of: [linkArrayMember],
    }),
    defineField({
      name: "footerLinks",
      title: "Footer Links (legacy)",
      type: "array",
      group: "footer",
      of: [linkArrayMember],
      deprecated: {
        reason: "Use Services Links and Company Links instead.",
      },
      readOnly: true,
      hidden: ({ value }) => !value || value.length === 0,
    }),
    defineField({
      name: "ctaTitlePrefix",
      title: "CTA Title — Prefix",
      type: "string",
      group: "cta",
      description: "White portion of the CTA headline.",
    }),
    defineField({
      name: "ctaTitleHighlight",
      title: "CTA Title — Highlight",
      type: "string",
      group: "cta",
      description: "Brand-colored portion of the CTA headline.",
    }),
    defineField({
      name: "ctaDescription",
      title: "CTA Description",
      type: "text",
      rows: 3,
      group: "cta",
    }),
    defineField({
      name: "ctaButton",
      title: "CTA Button",
      type: "object",
      group: "cta",
      fields: linkFields,
    }),
    defineField({
      name: "ctaPattern",
      title: "CTA Background Pattern",
      type: "image",
      group: "cta",
      description: "Upload or pick a pattern image from the media library.",
      options: { hotspot: true },
      fields: [
        defineField({
          name: "alt",
          title: "Alt Text",
          type: "string",
        }),
      ],
    }),
    defineField({
      name: "contactPhones",
      title: "Contact Phones",
      type: "array",
      group: "contact",
      of: [{ type: "string" }],
      description: "Shown in the contact information block and footer.",
    }),
    defineField({
      name: "contactEmails",
      title: "Contact Emails",
      type: "array",
      group: "contact",
      of: [{ type: "string" }],
      description: "Shown in the contact information block and footer.",
    }),
    defineField({
      name: "contactAddress",
      title: "Contact Address",
      type: "text",
      rows: 3,
      group: "contact",
    }),
    defineField({
      name: "contactEmail",
      title: "Contact Email (legacy)",
      type: "string",
      group: "contact",
      deprecated: {
        reason: "Use Contact Emails so multiple addresses can be listed.",
      },
      readOnly: true,
      hidden: ({ value }) => value === undefined,
    }),
    defineField({
      name: "contactPhone",
      title: "Contact Phone (legacy)",
      type: "string",
      group: "contact",
      deprecated: {
        reason: "Use Contact Phones so multiple numbers can be listed.",
      },
      readOnly: true,
      hidden: ({ value }) => value === undefined,
    }),
  ],
  preview: {
    prepare: () => ({ title: "Site Settings" }),
  },
});
